### ISSUE TITLE
Users won't have the repository available when they use the extension

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa-lua-vscode-extension#3]
Discussions up to this point have been about working with the extension while you're in the repository. But in practice a user would work in their own map / mod script, and they won't have the repository available to them unless they clone it themselves.

Is there a possibility that the extension clones the repository on first launch, and then adds all the information to the current Lua scope (that of the map script)?

**Comment by hahn-kev** [comment]
This is a good point. It's certainly something we should have a good solution for. 

Cloning the repo is one solution, but I wouldn't want to try and automate that, at least not without user consent first. There could also be a lot of corner cases and I feel like it's something that would require a lot of maintenance.

The obvious solution would be to write a guide, maybe even provide a zip as starting point with some scripts to help them get started. The main thing would be to configure the settings properly. This would be quite a bit of work on our end and for the user but not too bad, though it would end up with a lot of user support anyway I would guess.

The next solution, which would be some work but probably end up better for the user is to include the lua files directly in the extension. This is actually something the extension already does for some libraries, otherwise I wouldn't suggest it. From a simple check this would increase the size of the extension by 4mb or so but not very much. The up side of this is that it would be super simple and we'd only need to tell users of a few settings to use to make everything else work (which we could just change defaults to solve that also). The only real downside of this the version wouldn't always be up to date, but we could probably quite easily upgrade the version from time to time as needed. Also if someone needed a more up to date version they could also do that and just disable the included version.

**Comment by Garanas** [comment]
I'd be fine with either solution - I can make a video / a guide to help people setup the extension. My preference would be the second solution, especially as I think we can use Github actions to publish a new release of the extension at the ease of a click of a button. That would be required after each release.

**Comment by hahn-kev** [comment]
Alright, this should now be resolved. Can you test it out? just open a folder in vs code with the extension enabled and make a new lua file, it should prompt you to enable 3rd party libraries in the bottom right, allow it to do that and change settings. This dialog should pop up, select "Apply and Modify". After the workspace reloads and the extension parses all the files you should have support for FA in this mod folder.
![image](https://user-images.githubusercontent.com/4575355/172309674-fb7920c4-4610-4a1a-bfbd-83a5cacae05c.png)
